\newlabel{approaches}
\newlabel{catfunc}
\newlabel{complexity}
\newlabel{coredl}
\newlabel{evaluation}
\newlabel{exists}
\newlabel{expression}
\newlabel{fig1-10}
\newlabel{fig1-11}
\newlabel{fig1-12}
\newlabel{fig1-13}
\newlabel{fig1-1}
\newlabel{fig1-2}
\newlabel{fig1-3}
\newlabel{fig1-4}
\newlabel{fig1-5}
\newlabel{fig1-6}
\newlabel{fig1-7}
\newlabel{fig1-8}
\newlabel{fig1-9}
\newlabel{fig2-10}
\newlabel{fig2-11}
\newlabel{fig2-12}
\newlabel{fig2-13}
\newlabel{fig2-14}
\newlabel{fig2-15}
\newlabel{fig2-16}
\newlabel{fig2-17}
\newlabel{fig2-18}
\newlabel{fig2-1}
\newlabel{fig2-2}
\newlabel{fig2-3}
\newlabel{fig2-4}
\newlabel{fig2-5}
\newlabel{fig2-6}
\newlabel{fig2-7}
\newlabel{fig2-8}
\newlabel{fig2-9}
\newlabel{fig3-10}
\newlabel{fig3-11}
\newlabel{fig3-12}
\newlabel{fig3-13}
\newlabel{fig3-14}
\newlabel{fig3-15}
\newlabel{fig3-16}
\newlabel{fig3-1}
\newlabel{fig3-2}
\newlabel{fig3-3}
\newlabel{fig3-4}
\newlabel{fig3-5}
\newlabel{fig3-6}
\newlabel{fig3-7}
\newlabel{fig3-8}
\newlabel{fig3-9}
\newlabel{fig4-10}
\newlabel{fig4-11}
\newlabel{fig4-12}
\newlabel{fig4-13}
\newlabel{fig4-14}
\newlabel{fig4-1}
\newlabel{fig4-2}
\newlabel{fig4-3}
\newlabel{fig4-4}
\newlabel{fig4-5}
\newlabel{fig4-6}
\newlabel{fig4-7}
\newlabel{fig4-8}
\newlabel{fig4-9}
\newlabel{fpmethods}
\newlabel{higlevelhypo}
\newlabel{intersection}
\newlabel{mappings}
\newlabel{method}
\newlabel{reqdef}
\newlabel{reqdyn}
\newlabel{reqhie}
\newlabel{reqmath}
\newlabel{reqscale}
\newlabel{sec:opp}
\newlabel{specskb}
\newlabel{table1}
\newlabel{table2}
\newlabel{tablel02}
\newlabel{tablespecind}
