\newlabel{approaches}
\newlabel{expression}
\newlabel{fig1-10}
\newlabel{fig1-11}
\newlabel{fig1-12}
\newlabel{fig1-13}
\newlabel{fig1-1}
\newlabel{fig1-2}
\newlabel{fig1-3}
\newlabel{fig1-4}
\newlabel{fig1-5}
\newlabel{fig1-6}
\newlabel{fig1-7}
\newlabel{fig1-8}
\newlabel{fig1-9}
\newlabel{sec:opp}
\newlabel{table1}
\newlabel{table2}
