\newlabel{approaches}
\newlabel{complexity}
\newlabel{coredl}
\newlabel{exists}
\newlabel{expression}
\newlabel{fig1-10}
\newlabel{fig1-11}
\newlabel{fig1-12}
\newlabel{fig1-13}
\newlabel{fig1-1}
\newlabel{fig1-2}
\newlabel{fig1-3}
\newlabel{fig1-4}
\newlabel{fig1-5}
\newlabel{fig1-6}
\newlabel{fig1-7}
\newlabel{fig1-8}
\newlabel{fig1-9}
\newlabel{fig2-10}
\newlabel{fig2-11}
\newlabel{fig2-12}
\newlabel{fig2-13}
\newlabel{fig2-14}
\newlabel{fig2-15}
\newlabel{fig2-16}
\newlabel{fig2-17}
\newlabel{fig2-18}
\newlabel{fig2-1}
\newlabel{fig2-2}
\newlabel{fig2-3}
\newlabel{fig2-4}
\newlabel{fig2-5}
\newlabel{fig2-6}
\newlabel{fig2-7}
\newlabel{fig2-8}
\newlabel{fig2-9}
\newlabel{intersection}
\newlabel{reqdef}
\newlabel{reqdyn}
\newlabel{reqhie}
\newlabel{reqmath}
\newlabel{reqscale}
\newlabel{sec:opp}
\newlabel{table1}
\newlabel{table2}
